### ISSUE TITLE
Assistance Required for Resolving codeml Analysis Issues with Non-Multiples of Three in Sequence Length

### ISSUE THREAD

**Issue by HyeonseonPark** [abacus-gene/paml-tutorial#6]
Dear Ziheng Yang and Sandra,
I hope this message finds you well. I am currently engaged in a comparative genomic study aimed at identifying positively selected genes across multiple genomes. For this purpose, I am utilizing codeml from the PAML package to analyze several single-copy genes.

To enhance the accuracy and reliability of my analysis, I performed pal2nal for codon-based alignment, followed by trimming with Gblocks to refine the alignments. Despite these precautions, I encountered an error when attempting to run the M0 model analysis in codeml. The error indicates that the sequence length in some of the .phy files is not a multiple of three, which I understand is crucial for codon-based analyses.

Given your expertise and experience with codeml, I would greatly appreciate any guidance or suggestions you might have on how to address this issue. Is there a recommended approach to ensure that all sequences are of the appropriate length post-trimming, or any specific advice you could offer for handling such cases in the context of positive selection analysis?

I am eager to resolve this issue promptly and continue with my research. Any help or insights you could provide would be immensely valuable.

Thank you very much for your time and consideration. I look forward to your response.

Best regards,

Hyeonseon Park
Chungnam National University

**Comment by sabifo4** [comment]
Hi there!

I have just seen this issue, apologies for the late reply. As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki), the GitHub repository is aimed at issues related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this question should have been posted on the PAML discussion group (it is not a technical issue related to PAML nor, more specifically, to `CODEML` nor the scripts hosted in this `positive-selection` repository) please find below some guidelines to answer your question.

Please note that your questions are not related to `CODEML` or issues with `CODEML` or other PAML programs. More specifically, they are related to the usage of other tools such as `pal2nal`, `Gblock`, etc. If you follow the instructions we detailed [on a general step-by-step tutorial for data processing](https://github.com/abacus-gene/paml-tutorial/tree/main/positive-selection/00_data), you may find some guidelines with regards to how to make sure that the input sequence alignment that you use for `CODEML` is indeed a codon sequence alignment -- please note that this protocol is quite general and you may need to include additional filters/steps depending on the data you are using :)

Hope this helps!
Sandy

P.S.: If you have further non-technical questions, please post them in the [PAML discussion group](https://groups.google.com/g/pamlsoftware) :)
